/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { ApplicantService } from "../applicant.service";
import { ApplicantCreateInput } from "./ApplicantCreateInput";
import { Applicant } from "./Applicant";
import { ApplicantFindManyArgs } from "./ApplicantFindManyArgs";
import { ApplicantWhereUniqueInput } from "./ApplicantWhereUniqueInput";
import { ApplicantUpdateInput } from "./ApplicantUpdateInput";
import { ApplicationFindManyArgs } from "../../application/base/ApplicationFindManyArgs";
import { Application } from "../../application/base/Application";
import { ApplicationWhereUniqueInput } from "../../application/base/ApplicationWhereUniqueInput";

export class ApplicantControllerBase {
  constructor(protected readonly service: ApplicantService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Applicant })
  @swagger.ApiBody({
    type: ApplicantCreateInput,
  })
  async createApplicant(
    @common.Body() data: ApplicantCreateInput
  ): Promise<Applicant> {
    return await this.service.createApplicant({
      data: data,
      select: {
        createdAt: true,
        email: true,
        firstName: true,
        id: true,
        lastName: true,
        resume: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Applicant] })
  @ApiNestedQuery(ApplicantFindManyArgs)
  async applicants(@common.Req() request: Request): Promise<Applicant[]> {
    const args = plainToClass(ApplicantFindManyArgs, request.query);
    return this.service.applicants({
      ...args,
      select: {
        createdAt: true,
        email: true,
        firstName: true,
        id: true,
        lastName: true,
        resume: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Applicant })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async applicant(
    @common.Param() params: ApplicantWhereUniqueInput
  ): Promise<Applicant | null> {
    const result = await this.service.applicant({
      where: params,
      select: {
        createdAt: true,
        email: true,
        firstName: true,
        id: true,
        lastName: true,
        resume: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Applicant })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiBody({
    type: ApplicantUpdateInput,
  })
  async updateApplicant(
    @common.Param() params: ApplicantWhereUniqueInput,
    @common.Body() data: ApplicantUpdateInput
  ): Promise<Applicant | null> {
    try {
      return await this.service.updateApplicant({
        where: params,
        data: data,
        select: {
          createdAt: true,
          email: true,
          firstName: true,
          id: true,
          lastName: true,
          resume: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Applicant })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteApplicant(
    @common.Param() params: ApplicantWhereUniqueInput
  ): Promise<Applicant | null> {
    try {
      return await this.service.deleteApplicant({
        where: params,
        select: {
          createdAt: true,
          email: true,
          firstName: true,
          id: true,
          lastName: true,
          resume: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/applications")
  @ApiNestedQuery(ApplicationFindManyArgs)
  async findApplications(
    @common.Req() request: Request,
    @common.Param() params: ApplicantWhereUniqueInput
  ): Promise<Application[]> {
    const query = plainToClass(ApplicationFindManyArgs, request.query);
    const results = await this.service.findApplications(params.id, {
      ...query,
      select: {
        applicant: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,

        jobListing: {
          select: {
            id: true,
          },
        },

        status: true,
        submissionDate: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/applications")
  async connectApplications(
    @common.Param() params: ApplicantWhereUniqueInput,
    @common.Body() body: ApplicationWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      applications: {
        connect: body,
      },
    };
    await this.service.updateApplicant({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/applications")
  async updateApplications(
    @common.Param() params: ApplicantWhereUniqueInput,
    @common.Body() body: ApplicationWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      applications: {
        set: body,
      },
    };
    await this.service.updateApplicant({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/applications")
  async disconnectApplications(
    @common.Param() params: ApplicantWhereUniqueInput,
    @common.Body() body: ApplicationWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      applications: {
        disconnect: body,
      },
    };
    await this.service.updateApplicant({
      where: params,
      data,
      select: { id: true },
    });
  }
}
